// src/components/Filter.jsx
import {useActiveFilter, useFilters} from '../store/filter'

function FilterOption({filter}) {
  return (
    <option key={filter.name} value={filter}>
      {filter.text}
    </option>
  )
}
function Filter() {
  const [filters] = useFilters()
  const [activeFilter, setActiveFilter] = useActiveFilter()
  return (
    <div>
      <label htmlFor="filter">Data displayed : </label>
      <select id="filter">
        {filters.map(filter => 
          <FilterOption filter={filter}></FilterOption>
        )}
      </select>
    </div>
  )
}

export default Filter

// src/components/Filter.vue
<template>
  <div>
    <label for="filter">Data displayed : </label>
    <select v-model="activeFilter" id="filter">
      <option v-for="filter in filters" :key="filter.name" :value="filter">{{filter.text}}</option>
    </select>
  </div>
</template>

<script>
import {useActiveFilter, useFilters} from '@/state/filter.js'

export default {
  name: "Filter",
  setup() {
    const activeFilter = useActiveFilter()
    const filters = useFilters()

    return {
      activeFilter,
      filters,
    }
  },
}
</script>

<style scoped>

</style>
